config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
root "flights#index"
resources :flights
resources :bookings


  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/airport.rb
class Airport < ApplicationRecord
  has_many :departing_flights, class_name: 'Flight', foreign_key: 'departure_airport_id'
  has_many :arriving_flights, class_name: 'Flight', foreign_key: 'arrival_airport_id'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :flight
  has_many :booking_passengers, inverse_of: :booking
  has_many :passengers, through: :booking_passengers

  accepts_nested_attributes_for :passengers, reject_if: :all_blank, allow_destroy: true


end

app/models/booking_passenger.rb
class BookingPassenger < ApplicationRecord
  belongs_to :booking,  inverse_of: :booking_passengers
  belongs_to :passenger,  inverse_of: :booking_passengers
end

app/models/flight.rb
class Flight < ApplicationRecord
  belongs_to :arrival_airport, class_name: 'Airport', foreign_key: 'arrival_airport_id'
  belongs_to :departure_airport, class_name: 'Airport', foreign_key: 'departure_airport_id'


  has_many :bookings
  has_many :passengers, through: :bookings


  def formatted_flight_duration
    flight_duration.strftime("%H:%M:%S")
  end



  def self.selected_flight(flight_search)
    where(departure_airport_id: flight_search["departure_airport"], arrival_airport_id: flight_search["arrival_airport"])
  end

end

app/models/passenger.rb
class Passenger < ApplicationRecord
  has_many :booking_passengers, inverse_of: :passenger
  has_many :bookings, through: :booking_passengers
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController

  def new
      #puts "booking new begin  : #{@booking.inspect}"
      @flights = params[:flight]
      #puts "@flights in bookings new : #{@flights.inspect}"
      #puts "booking Params flight: #{params[:flight]}"
      @pass = params[:flight]["passengers"].to_i
      #puts "@pass : #{@pass.inspect}"
      @flight = Flight.find_by(id: @flights[:selected_flight_id])
      puts "@flights in bookings new : #{@flights.inspect}"
      @booking = Booking.new
      @booking.passengers.build
  end

  def create
    puts "booking params : #{booking_params}"
    #@booking = Booking.new(booking_params)
    #@bookingpassengersb = @booking.passengers.build
    #puts "booking new end  : #{@bookingpassengersb.inspect}"
    #puts "booking.passengers : #{@booking.passengers.inspect}"
    @booking = Booking.new(booking_params)

    if @booking.save
      redirect_to @booking, notice: 'Booking was successfully created.'
      PassengerMailer.with(booking: @booking, flight: @flight).booking_email.deliver_now
    else
      puts @booking.errors.full_messages
    end
  end

  def show
    @booking = Booking.find(params[:id])
  end


  private
  def booking_params
    params.require(:booking).permit(:flight_id, passengers_attributes: [:id, :_destroy, :name, :email])
  end
end

app/controllers/flights_controller.rb
class FlightsController < ApplicationController


  def index
    if params[:flight].present?
      @flight_search = params[:flight]
      @flights = Flight.selected_flight(params[:flight])
      #puts "Params flight: #{params[:flight]}"
      #puts @flights.inspect
      #puts "flight params : #{flight_params["departure_airport"]}"
      # @selected_flights = Flight.selected_flight
      #puts "flight_search : #{@flight_search}"
      #puts "@flights : #{@flights.inspect}"
    else
    @flights = Flight.all
    end
  end


  private
  def flight_params
    params.require(:flight).permit(:start,:departure_airport, :arrival_airport)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/helpers/flights_helper.rb
module FlightsHelper
end

app/views/bookings/_passenger_form.html.erb
<div class="nested-form-wrapper" data-new-record="<%= f.object.new_record? %>">
  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :email %>
  <%= f.text_field :email %>

  <button type="button" data-action="nested-form#remove" data-nested-form-target="removeButton">Remove todo</button>

  <%= f.hidden_field :_destroy %>
</div>

app/views/bookings/new.html.erb
 <%= form_with model: @booking, data:{ controller: 'nested-form', nested_form_wrapper_selector_value: '.nested-form-wrapper' }, url: bookings_path do |f| %>
  <%= f.hidden_field :flight_id, value: @flight.id %>

 <template data-nested-form-target="template">
    <%= f.fields_for :passengers, Passenger.new, child_index: 'NEW_RECORD' do |passenger_fields| %>
      <%= render "passenger_form", f: passenger_fields %>
    <% end %>
  </template>




   <%= f.fields_for :passengers do |passenger_fields| %>
    <%= render "passenger_form", f: passenger_fields %>
  <% end %>

  <div data-nested-form-target="target"></div>

  <button type="button" data-action="nested-form#add">Add passenger</button>

 <%= f.submit 'submit' %>
<% end %>

app/views/bookings/show.html.erb
<h1>Booking Details</h1>

<p><strong>Departure Airport:</strong> <%= @booking.flight.departure_airport.code %></p>
<p><strong>Arrival Airport:</strong> <%= @booking.flight.arrival_airport.code %></p>
<p>Scheduled: <%= @booking.flight.start %></p>
<p>Flight Duration: <%= @booking.flight.formatted_flight_duration %></p>
<hr>
<h2>Passengers</h2>
<% @booking.passengers.each do |passenger| %>
  <p><strong>Name:</strong> <%= passenger.name %></p>
  <p><strong>Email:</strong> <%= passenger.email %></p>
<% end %>

app/views/flights/index.html.erb
<h1>Flights</h1>

<%= form_with model: @flights, method: :get, url: flights_path do |form| %>
  <%= form.collection_select :departure_airport, Airport.all, :id, :code %>
  <%= form.collection_select :arrival_airport, Airport.all, :id, :code %>
  <%= form.collection_select :start, Flight.all, :id, :start %>
  <%= form.label :"Number of passengers :" %>
  <%= form.select :passengers, (1..4) %>
  <%= form.submit "Search" %>
  <%= link_to "back to main", root_path %>
<% end %>
<hr>



<% if params[:flight].present? %>
  <%if @flights.empty? %>
    <% departure_airport = Airport.find_by(id: params[:flight]["departure_airport"]) %>
    <% arrival_airport = Airport.find_by(id: params[:flight]["arrival_airport"]) %>
    No flights found for Departure Airport: <%= departure_airport.code %>, Arrival Airport: <%= arrival_airport.code %>
  <% else %>
    <%= form_with model: @flights, method: :get, url: new_booking_path do |form| %>
      <% @flights.each do |flight| %>
        <p> <%= form.label "flight_#{flight.id}", "Departure Airport: #{flight.departure_airport.code}" %></p>
        <p> <%= form.label "flight_#{flight.id}", "Arrival Airport: #{flight.arrival_airport.code}" %></p>
        <p> <%= form.label "flight_#{flight.id}", "Scheduled: #{flight.start}" %></p>
        <p> <%= form.label "flight_#{flight.id}", "Flight Duration: #{flight.formatted_flight_duration}" %></p>
        <p> <%= form.radio_button :selected_flight_id, flight.id, id: "flight_#{flight.id}" %></p>
            <%= form.hidden_field :passengers, value: params[:flight]["passengers"] %>
            <%= form.submit "Confirm selected" %>
        <hr>
        <% end %>
      <% end %>
    <% end %>
  <% else %>

<% @flights.group_by(&:departure_airport).each do |departure_airport, flights| %>
  <div style="width: 33.33%; float: left;">
    <h2><%= departure_airport.code %></h2>
    <% flights.each do |flight| %>
      <p><strong>Departure Airport:</strong> <%= flight.departure_airport.code %></p>
      <p><strong>Arrival Airport:</strong> <%= flight.arrival_airport.code %></p>
      <p><strong>Scheduled:</strong> <%= flight.start %></p>
      <p><strong>Flight Duration:</strong> <%= flight.formatted_flight_duration %></p>
      <hr>
    <% end %>
  </div>
<% end %>



<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FlightBooker</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>